"""skill deleted

Revision ID: cb9ed6bbeed6
Revises: 5063670b0983
Create Date: 2024-08-29 17:28:07.722339

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9ed6bbeed6'
down_revision: Union[str, None] = '5063670b0983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
