"""test 2

Revision ID: bb45cfd775f3
Revises: c88b4706b9c9
Create Date: 2024-09-11 12:19:45.824807

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb45cfd775f3'
down_revision: Union[str, None] = 'c88b4706b9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveltemp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveltemp',
    sa.Column('descryption', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('journey_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], name='traveltemp_journey_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='traveltemp_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'journey_id', name='traveltemp_pkey')
    )
    # ### end Alembic commands ###
