"""test

Revision ID: c88b4706b9c9
Revises: 79852de0b0c2
Create Date: 2024-09-11 12:19:17.012892

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88b4706b9c9'
down_revision: Union[str, None] = '79852de0b0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveltemp',
    sa.Column('descryption', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'journey_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveltemp')
    # ### end Alembic commands ###
