"""skill added

Revision ID: e078b5d7af1d
Revises: cb9ed6bbeed6
Create Date: 2024-09-01 21:27:41.519964

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e078b5d7af1d'
down_revision: Union[str, None] = 'cb9ed6bbeed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'level')
    # ### end Alembic commands ###
